/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Code.*;
import java.awt.Graphics;
import java.util.LinkedList;

/**
 *
 * @author 4NDR35
 */
public class Interface extends javax.swing.JPanel {

    private LinkedList<Point> point = new LinkedList<>();
    Control c;

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        

    }

    public void SetControl(Control c) {

        this.c = c;
        this.paintComponent(this.getGraphics());
    }
    
    public  void SetPoints (LinkedList<Point> p){
        this.point = p;
        this.paintComponent(this.getGraphics());
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        if(!(point.isEmpty())){
            for (Point point1 : point) {
                point1.Draw(g);
            }
        }
        if(c != null && c.getT().getRoot() != null){
        c.Lines(g, c.getT().getRoot());
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * @return the point
     */
    public LinkedList<Point> getPoint() {
        return point;
    }

    /**
     * @param point the point to set
     */
    public void setPoint(LinkedList<Point> point) {
        this.point = point;
    }

    /**
     * @return the Horizontal
     */
}
